services:
  proxy_c2:
      #image: ubuntu/apache2
      build:
        context: ./proxy
        dockerfile: dockerfile
      volumes:
        - ./proxy/DummyFolder:/var/www
        - ./proxy/DummyFolder:/usr/share/apache2
      networks:
        - bye_net
  portal_c2:
    image: wordpress:php8.2-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - bye_net

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bye_net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - db
    networks:
      - bye_net

volumes:
  db_data:

networks:
  bye_net:
    external: true