version: '3.8'

services:
  proxy_c3:
    #image: ubuntu/apache2
    build:
      context: ./proxy
      dockerfile: dockerfile
    networks:
      - bye_net
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - bye_net

  portal_c3:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    #ports:
    # - "8083:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306 #excluir essa porta antes da execução (teste)
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_SITE_URL: http://portal.cliente3.br
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - bye_net

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    restart: always
    #ports:
    #  - "8084:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - bye_net

networks:
  bye_net:
    external: true
