version: '3.8'

services:
  proxy_c3:
    build:
      context: ./proxy
      dockerfile: dockerfile
    restart: always
    depends_on:
      - portal_c3
    networks:
      - bye_net

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - bye_net

  portal_c3:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - bye_net

  phpmyadmin_c3:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - bye_net

networks:
  bye_net:
    external: true
